### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by bachym** [JettChenT/scan-for-webcams#117]
sfw search webcamXP --debug=True
loc:True, check_empty:True, tag:True
⠙ Looking for possible servers...Traceback (most recent call last):
  File "/home/bachym/.local/bin/sfw", line 8, in <module>
    sys.exit(Main())
  File "/home/bachym/.local/lib/python3.8/site-packages/scanforwebcams/universal.py", line 6, in Main
    fire.Fire(CLI)
  File "/home/bachym/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bachym/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/bachym/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/bachym/.local/lib/python3.8/site-packages/scanforwebcams/cli.py", line 38, in search
    self.scanner.scan_preset(preset, check, tag, loc, debug=debug)
  File "/home/bachym/.local/lib/python3.8/site-packages/scanforwebcams/search.py", line 166, in scan_preset
    self.scan(**config)
  File "/home/bachym/.local/lib/python3.8/site-packages/scanforwebcams/search.py", line 90, in scan
    self.init_clarifai()
  File "/home/bachym/.local/lib/python3.8/site-packages/scanforwebcams/search.py", line 43, in init_clarifai
    self.clarifai_app = ClarifaiApp(api_key=self.CLARIFAI_API_KEY)
  File "/home/bachym/.local/lib/python3.8/site-packages/clarifai/rest/client.py", line 124, in __init__
    self.models = Models(self.api, self.solutions)  # type: Models
  File "/home/bachym/.local/lib/python3.8/site-packages/clarifai/rest/client.py", line 1068, in __init__
    self.model_id_cache = self.init_model_cache()
  File "/home/bachym/.local/lib/python3.8/site-packages/clarifai/rest/client.py", line 1088, in init_model_cache
    model_type = m.output_info['type']
KeyError: 'type'

**Comment by JettChenT** [comment]
Hello, sorry for not working on this project for a long time. I've updated this repo with grpc support and  switched to a new installation method(similar to [sherlock](https://github.com/sherlock-project/sherlock)). 

Installing this project again(see the new README) should solve your problem!
