### ISSUE TITLE
Invalid Syntax Error

### ISSUE THREAD

**Issue by EmileDiaz** [JettChenT/scan-for-webcams#15]
I get an invalid syntax error. Please see details below.

Can anyone advise why this is? I followed all directions, including the install of the Shodan and Clarifai API keys.

Thank you.

I am getting an error during the requirements command, that I have placed below

```
root@kali:~/scan-for-webcams# python MJPG.py
Traceback (most recent call last):
  File "MJPG.py", line 1, in 
    from search import Scanner
  File "/root/scan-for-webcams/search.py", line 7
    from rich import print
                         ^
SyntaxError: invalid syntax
root@kali:~/scan-for-webcams# python webcamXP.py
Traceback (most recent call last):
  File "webcamXP.py", line 1, in 
    from search import Scanner
  File "/root/scan-for-webcams/search.py", line 7
    from rich import print
                         ^
SyntaxError: invalid syntax
root@kali:~/scan-for-webcams# 
```

This may help: I get the following when I am running the requirements command:

```
root@kali:~/scan-for-webcams# pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. 
Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. 
More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                                                                                            
Requirement already satisfied: shodan==1.23.0 in /usr/local/lib/python2.7/dist-packages/shodan-1.23.0-py2.7.egg (from -r requirements.txt (line 1)) (1.23.0)
Collecting requests==2.24.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
ERROR: Could not find a version that satisfies the requirement rich==6.0.0 (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for rich==6.0.0 (from -r requirements.txt (line 3))
```

**Comment by JettChenT** [comment]
This program does not support python 2. Try using python 3
